require:
  - rubocop-performance

AllCops:
  Include:
    - "**/*.rb"
    - "**/Gemfile"
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Layout/LineLength:
  Max: 255

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/IndentationConsistency:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/AccessModifierIndentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - lib/counter/base.rb
    - lib/formatter/base.rb
    - lib/counter/base.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/smart_pension.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/smart_pension.rb

Metrics/ParameterLists:
  Exclude:
    - lib/smart_pension.rb
